testons7

diff --git a/.github/workflows/webapp.yaml b/.github/workflows/webapp.yaml
--- a/.github/workflows/webapp.yaml
+++ b/.github/workflows/webapp.yaml
@@ -23,7 +23,17 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: "eu-west-1"
+    
+    - name: Check if webapp/ directory exists and contains files
+      run: |
+        if [ -d "webapp" ] && [ "$(ls -A webapp)" ]; then
+          echo "webapp/ directory exists and contains files."
+        else
+          echo "webapp/ directory is missing or empty. Please check."
+          exit 1
+        fi
+
     - name: Deploy to AWS S3
       run: |
         echo "Uploading files to S3..."
-        aws s3 cp webapp/ s3://lecloudfacile-rockkoue-225/  --region eu-west-1
+        aws s3 cp webapp/ s3://lecloudfacile-rockkouexs-225/  --region eu-west-1
